name: Release to npm

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.2.20"

      - name: Install
        run: bun install

      - name: Publish to npm
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
        run: bun loom-release publish
